"""
Safety layer — Week 2 version.

This is a HARD GATE, not a prompt instruction. It runs before the LLM is ever called.
If it flags a message as high risk, the LLM is not invoked for that turn at all; a fixed,
pre-written response with crisis resources is returned instead, and the event is logged.

A learned classifier (reusing the emotion-model backbone with a risk-detection head) is
added in Week 7-8 to run alongside this keyword matcher and catch what phrasing patterns miss.
Until then, this deliberately errs toward over-inclusion — a false positive here just means
someone sees a resource card they didn't strictly need; a false negative is unacceptable.
"""
import re
from dataclasses import dataclass
from enum import Enum

import httpx

from app.core.config import settings


class RiskLevel(str, Enum):
    none = "none"
    low = "low"
    medium = "medium"
    high = "high"


_RISK_ORDER = {RiskLevel.none: 0, RiskLevel.low: 1, RiskLevel.medium: 2, RiskLevel.high: 3}


@dataclass
class SafetyCheckResult:
    risk_level: RiskLevel
    trigger_type: str  # 'keyword' for now
    matched_category: str | None


# Patterns are grouped by risk tier. This list is intentionally broad rather than clever —
# keep it short, readable, and easy for a human reviewer to audit and extend.
_HIGH_RISK_PATTERNS = [
    r"\bkill myself\b",
    r"\bend my life\b",
    r"\bwant to die\b",
    r"\bsuicid\w*\b",
    r"\bnot want(ing)? to (be alive|live anymore)\b",
    r"\bplan to (hurt|kill) myself\b",
    r"\bno reason to (live|go on)\b",
]

_MEDIUM_RISK_PATTERNS = [
    r"\bhurt(ing)? myself\b",
    r"\bself[- ]harm\b",
    r"\bcan'?t (take|do) (this|it) anymore\b",
    r"\beveryone would be better off without me\b",
    r"\bhopeless\b",
]

_HIGH_RE = re.compile("|".join(_HIGH_RISK_PATTERNS), re.IGNORECASE)
_MEDIUM_RE = re.compile("|".join(_MEDIUM_RISK_PATTERNS), re.IGNORECASE)


def check_message_safety(content: str) -> SafetyCheckResult:
    if _HIGH_RE.search(content):
        return SafetyCheckResult(risk_level=RiskLevel.high, trigger_type="keyword", matched_category="high_risk")
    if _MEDIUM_RE.search(content):
        return SafetyCheckResult(risk_level=RiskLevel.medium, trigger_type="keyword", matched_category="medium_risk")
    return SafetyCheckResult(risk_level=RiskLevel.none, trigger_type="keyword", matched_category=None)


async def check_message_safety_combined(content: str) -> SafetyCheckResult:
    """
    Week 7-8 upgrade: runs the keyword matcher (instant, deterministic) alongside the learned
    risk classifier served by ml-service (catches phrasing patterns keywords miss), and takes
    the HIGHER of the two risk levels. If ml-service is unreachable, this fails safe by falling
    back to keyword-only rather than skipping the safety check entirely.
    """
    keyword_result = check_message_safety(content)

    try:
        async with httpx.AsyncClient(timeout=3.0) as client:
            response = await client.post(f"{settings.ML_SERVICE_URL}/predict/risk-classifier", json={"text": content})
            response.raise_for_status()
            classifier_risk = RiskLevel(response.json()["risk_level"])
    except (httpx.HTTPError, KeyError, ValueError):
        return keyword_result  # fail safe: keep the keyword-based result rather than erroring out

    if _RISK_ORDER[classifier_risk] > _RISK_ORDER[keyword_result.risk_level]:
        return SafetyCheckResult(risk_level=classifier_risk, trigger_type="classifier", matched_category="model_flagged")
    return keyword_result


# Fixed, carefully worded response — never generated by the LLM. Locale-specific resources
# should be expanded over time (this is US-centric as a starting point).
CRISIS_RESPONSE = (
    "It sounds like you might be going through something really painful right now, and I want "
    "to make sure you get support that can actually help in this moment — that's not something "
    "I'm able to provide as an AI.\n\n"
    "If you're in the US, you can call or text 988 (Suicide & Crisis Lifeline) anytime, day or "
    "night. If you're outside the US, please look up your local crisis line — I can help you "
    "find one if you tell me your country.\n\n"
    "If you're in immediate danger, please contact local emergency services.\n\n"
    "I'm still here if you want to keep talking, but I wanted to put those resources in front of "
    "you first."
)

MEDIUM_RISK_PROMPT_ADDENDUM = (
    "\n\nIMPORTANT CONTEXT: this message showed signs of significant emotional distress. "
    "Gently acknowledge the difficulty of what they're describing, do not minimize it, and "
    "if it feels natural, mention that support like the 988 Suicide & Crisis Lifeline (US) "
    "exists — without being preachy or repeating this every message. Do not diagnose. "
    "Do not claim to be a therapist."
)
